// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SyncMsg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace SyncMsg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgSyncTank : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ex")]
        public float Ex { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ey")]
        public float Ey { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ez")]
        public float Ez { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public float turretY { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgFire : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ex")]
        public float Ex { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ey")]
        public float Ey { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ez")]
        public float Ez { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MsgHit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string targetId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"z")]
        public float Z { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"hp")]
        public int Hp { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"damage")]
        public int Damage { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
